import "@/styles/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SiteHeader from "@/components/layouts/site-header"
import MainNav from "@/components/layouts/main-nav"
import SiteFooter from "@/components/layouts/site-footer"
import { Provider } from "@/components/layouts/provider"
import BackToTopButton from '@/components/ui/backToTopButton'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider attribute="class" defaultTheme="system" enableSystem>
        <MainNav/>
        <SiteHeader/>
        <div>{children}</div>
        <BackToTopButton />
        <SiteFooter/>
        </Provider>
        </body>
    </html>
  )
}
