
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SiteHeader from "@/components/layouts/site-header";
import MainNav from "@/components/layouts/main-nav";
import SiteFooter from "@/components/layouts/site-footer";
import { Provider } from "@/components/layouts/provider";
import BackToTopButton from "@/components/ui/backToTopButton";
const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import Test from "@/components/layouts/test";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body 
      className={cn(
        "",
        inter.className
      )}>
        <Provider attribute="class" defaultTheme="system" enableSystem>
          <MainNav />
          {/* <SiteHeader /> */}
          <Test/>
          <div className="2xl:container mx-auto max-w-[85rem]">{children}</div>
          <BackToTopButton />
          <SiteFooter />
        </Provider>
      </body>
    </html>
  );
}
